version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Install newest npm
      - npm install --silent --no-progress -g npm
      - echo Install dependencies
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
    - package.json
    - package-lock.json
    - .build/**/*
    - .sst/*
    - client/dist/*
    - buildspec-deploy.yml
