# Do not change version. This is the version of aws buildspec, not the version of your buildspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Install dependencies
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
