version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install --silent --no-progress -g npm
  pre_build:
    commands:
      - echo Install dependencies
      - npm install
  build:
    commands:
      - npm run deploy -- --stage test --region eu-central-1